name: Project Build

on:
  push:
  pull_request:
    branches: [ main ]

env:
  SOLUTION_NAME: 'MetamaskSetup.Playwright.sln'

jobs:
  build-and-test:
    strategy:
      matrix:
        framework: ["net8.0"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-1.49.0

      - name: Build Solution
        run: dotnet build ${{ env.SOLUTION_NAME }} --framework ${{ matrix.framework }} --property WarningLevel=0

      - name: Install Playwright Chromium
        run: pwsh tests/MetamaskSetup.Playwright.Tests/bin/Debug/net8.0/playwright.ps1 install chromium

      - name: Install Xvfb
        run: sudo apt-get update -qq && sudo apt-get install -y -qq xvfb

      - name: Run all tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          xvfb-run -a dotnet test tests/MetamaskSetup.Playwright.Tests/MetamaskSetup.Playwright.Tests.csproj
          --framework ${{ matrix.framework }}
          --no-build
          --logger "console;verbosity=normal"
