name: Publish to NuGet

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN}}
      
      - name: Build the package
        run: dotnet build --configuration Release MetamaskSetup.Playwright.csproj /p:Version=${{ github.event.release.tag_name }}
      
      - name: Create the package
        run: dotnet pack --configuration Release MetamaskSetup.Playwright.csproj /p:Version=${{ github.event.release.tag_name }}
      
      - name: Upload NuGet package as release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/bin/Release/*.nupkg
            **/bin/Release/*.snupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish the package to NuGet
        run: dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate
